# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/
dist: trusty
sudo: required

language: php

# Define the php versions against we want to test our code
php:
    - 7.0

env:
  global:
    - COVERALLS_RUN_LOCALLY=1
#    - secure: "KCRVNNrsPVX8aBkWh2MuyAVhlXt1J/igU0dVMFGJRb3/wM7dzqQqICnzQ5Y0e6PR8Lr8xclovFhvia4oQbc+IPgJxR5dB9zuQ6MMoEdkOMuAyIyUeyHZWtpbxIZ45x10MlYfDoA2jNR26/1nvPe6DWzfS/CeCqj93czo7T34T98mdMdIAozAjFuhTkOz+td3cY+YTvCwkF5zo6ImtQkoH0Wy+Sgn2p7Eu7+eTVEn+4BpFj9cbhutN9ebVhGWbKouEKIOVLR8+BaAEBWAsFMs8FdY3sETnrlZ0cAXbBy6gnkmGTRZDvEb2YCWZd1Yhf15c73uxxVlR5KHxwtQ4D0mg2hY47VE/zgRKKonTtHo44dnsUpJIFEUZNU6fhczUTZhXuy1PyHS98SU5CEreziJiySYHefS5Q5kdQKWzdPrn6ppHMdU/bKZHBwhD0OGd2Scn7/s4Co/jNepYMLya1yz0jegvqYJdMtSfCqeCQTI7jPDDFN813W9e8y8R4QMzVpFq23MtTONubfNgqiARuCd5qmOFvq1FaCgeUrG6jD1BCFnAobQt2MjvIsClGWUyau0NJNfQIxinkox/gAy4pWYe4w3OicKr+b/Vvx3qdXH6RhkGTAk4CNQNzrnNK15ZoJgJ/eQIFqnKUjNLGYmJeWFUNbDBFz8AbMu3SZXLOxUSzw="

addons:
  sonarcloud:
    organization: "markpthomas-github"
    token: "KCRVNNrsPVX8aBkWh2MuyAVhlXt1J/igU0dVMFGJRb3/wM7dzqQqICnzQ5Y0e6PR8Lr8xclovFhvia4oQbc+IPgJxR5dB9zuQ6MMoEdkOMuAyIyUeyHZWtpbxIZ45x10MlYfDoA2jNR26/1nvPe6DWzfS/CeCqj93czo7T34T98mdMdIAozAjFuhTkOz+td3cY+YTvCwkF5zo6ImtQkoH0Wy+Sgn2p7Eu7+eTVEn+4BpFj9cbhutN9ebVhGWbKouEKIOVLR8+BaAEBWAsFMs8FdY3sETnrlZ0cAXbBy6gnkmGTRZDvEb2YCWZd1Yhf15c73uxxVlR5KHxwtQ4D0mg2hY47VE/zgRKKonTtHo44dnsUpJIFEUZNU6fhczUTZhXuy1PyHS98SU5CEreziJiySYHefS5Q5kdQKWzdPrn6ppHMdU/bKZHBwhD0OGd2Scn7/s4Co/jNepYMLya1yz0jegvqYJdMtSfCqeCQTI7jPDDFN813W9e8y8R4QMzVpFq23MtTONubfNgqiARuCd5qmOFvq1FaCgeUrG6jD1BCFnAobQt2MjvIsClGWUyau0NJNfQIxinkox/gAy4pWYe4w3OicKr+b/Vvx3qdXH6RhkGTAk4CNQNzrnNK15ZoJgJ/eQIFqnKUjNLGYmJeWFUNbDBFz8AbMu3SZXLOxUSzw="
#      secure: "KCRVNNrsPVX8aBkWh2MuyAVhlXt1J/igU0dVMFGJRb3/wM7dzqQqICnzQ5Y0e6PR8Lr8xclovFhvia4oQbc+IPgJxR5dB9zuQ6MMoEdkOMuAyIyUeyHZWtpbxIZ45x10MlYfDoA2jNR26/1nvPe6DWzfS/CeCqj93czo7T34T98mdMdIAozAjFuhTkOz+td3cY+YTvCwkF5zo6ImtQkoH0Wy+Sgn2p7Eu7+eTVEn+4BpFj9cbhutN9ebVhGWbKouEKIOVLR8+BaAEBWAsFMs8FdY3sETnrlZ0cAXbBy6gnkmGTRZDvEb2YCWZd1Yhf15c73uxxVlR5KHxwtQ4D0mg2hY47VE/zgRKKonTtHo44dnsUpJIFEUZNU6fhczUTZhXuy1PyHS98SU5CEreziJiySYHefS5Q5kdQKWzdPrn6ppHMdU/bKZHBwhD0OGd2Scn7/s4Co/jNepYMLya1yz0jegvqYJdMtSfCqeCQTI7jPDDFN813W9e8y8R4QMzVpFq23MtTONubfNgqiARuCd5qmOFvq1FaCgeUrG6jD1BCFnAobQt2MjvIsClGWUyau0NJNfQIxinkox/gAy4pWYe4w3OicKr+b/Vvx3qdXH6RhkGTAk4CNQNzrnNK15ZoJgJ/eQIFqnKUjNLGYmJeWFUNbDBFz8AbMu3SZXLOxUSzw="
#      secure: $SONAR_TOKEN   # Specified as SONAR_TOKEN in Repository Settings w/o encryption

install:
  # Install composer packages
  - composer install --prefer-dist --no-interaction --no-progress

# Create a storage folder for coverage report
before_script:
  - mkdir -p build/logs
  - ls -al

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - sonar-scanner -X

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# You can delete the cache using travis-ci web interface
cache:
  directories:
    - 'vendor'
    - '$HOME/.cache/composer'
    - '$HOME/.sonar/cache'